### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by CapSel** [flathub/com.slack.Slack#107]
According to logs "processed" by someone from Slack the problem is with resolving domains like app.slack.com.
Slack works when used via browser, slack-desktop (btw I use Arch ;) from AUR works.

I don't have firewall other than default from docker without containers.

I tried installing with flatpak in (?) user or system - same result.

I'm using systemd-resolvd and my /etc/resolv.conf is empty. After placing there some nameserver slack loads. It's not permanent solution as systemd or NetworkManager are going to replace the file.

**Comment by WhyNotHugo** [comment]
Why is your `/etc/resolv.conf` empty? [The instructions for setting up `systemd-resolved` say you need to symlink that file](https://wiki.archlinux.org/title/Systemd-resolved#DNS):

    ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

**Comment by evan-a-a** [comment]
Closing due to age.
