### ISSUE TITLE
Quits after about 30 seconds

### ISSUE THREAD

**Issue by subpop** [flathub/com.slack.Slack#108]
## Description

On Fedora 33, using the KDE Spin, the Slack flatpak quits after about 30 seconds.

## Steps to Reproduce

1. Install Fedora 33 KDE Spin
2. Install com.slack.Slack `flatpak --user install com.slack.Slack`
3. `flatpak run com.slack.Slack`

## Expected Results

The application should run until I quit it.

## Actual Results

It quits after about 30 seconds.

## Notes

I have only seen this on the Fedora 33 KDE Spin. I've run the same flatpak on Pop!_OS (so, GNOME on X11), and Fedora 33 Workstation (so, GNOME on Wayland) and it runs fine. I haven't tried another KDE distribution yet.

I get this in my log journal when it quits:

```
Jan 19 10:21:13 thelio kwin_x11[1762]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1377, resource id: 113246215, major code: 15 (QueryTree), minor code: 0
```

**Comment by subpop** [comment]
Just had an opportunity to try this on a KDE neon 5.20.5 install; the same behavior happens. It quits after about 30 seconds.

**Comment by subpop** [comment]
For fun, I installed Plasma on Pop!_OS and the same thing happens. I also removed my ~/.config and logged in again, thinking it might be a problem caused by my Plasma settings, but it still happens.

**Comment by subpop** [comment]
Well, I did the whole "nuke & pave" and started a new home directory, and now on a fresh install of the flatpak, it's working. :(

**Comment by jeana-redhat** [comment]
I was having the same problem after switching my Fedora 35 from Gnome to KDE yesterday. I completely uninstalled the Slack flatpak with `flatpak uninstall --delete-data com.slack.Slack`, then reinstalled. So far, I think it is working ok (signed in and running for 3+ minutes). Hope this helps anyone else who stumbles upon this search :bow:

**Comment by evert** [comment]
Also had to do this after an update to Fedora 38. For months I was able to start slack with the command line to work around this, but finally did the nuke & reinstall to get rid of this issue.

**Comment by subpop** [comment]
In retrospect, I believe this is caused by the `com.slack.Slack` flatpak not having `background` permissions. If this occurs, check to see if `com.slack.Slack` has the `background` permission:

```
flatpak permission-show com.slack.Slack
```

The output should include the line:

```
background background com.slack.Slack yes                          0x00
```

If it does not, set it explicitly to `yes` or reset the permission and let the desktop prompt you again:

```
flatpak permission-set background com.slack.Slack yes
```

```
flatpak permission-reset com.slack.Slack
```

**Comment by evert** [comment]
Well, that might explain why Steam *also* crashes for me and Element used to. Gonna try setting that to Yes, thanks!

**Comment by evert** [comment]
The full command appears to be:

    flatpak permission-set background background com.slack.Slack yes

And it _did_ also fix my issues with steam, so thank you very much! My #1 issue with Fedora
