### ISSUE TITLE
Why disable GPU?

### ISSUE THREAD

**Issue by orschiro** [flathub/com.slack.Slack#11]
Hey guys, 

Just noticed that the desktop file contains the following parameter:

    Exec=/usr/bin/slack --disable-gpu %U

What's the reason for disabling the GPU?

Thanks!

**Comment by TingPing** [comment]
The desktop file is provided by Slack themselves so that is a question for them. I presume they encountered bugs on some drivers and took the easy solution.

**Comment by orschiro** [comment]
@TingPing going to ask the Slack devs to explain and comment here. Thanks!

**Comment by orschiro** [comment]
Heard back from the Slack devs:

> Hi Robert,
Thanks for writing in! We disable GPU for the Linux desktop app by default to speed up processing. However, some users see better performance by using the GPU. It's an issue we are investigating.
I'm afraid I can't comment on the site you mentioned, but feel free to pass this on.
Thanks,
Simone

**Comment by lpryszcz** [comment]
I've noticed that recently slack uses GPU, which is something I don't want, because GPU is used for computation mainly. 
To disable GPU in slack open `/usr/share/applications/slack.desktop` and edd `--disable-gpu` to `Exec` line.

**Comment by TingPing** [comment]
> To disable GPU in slack open /usr/share/applications/slack.desktop and edd --disable-gpu to Exec line.

This is a flatpak package...

You can copy `/var/lib/flatpak/exports/share/applications/com.slack.Slack.desktop` to `~/.local/share/applications` in that case.
