### ISSUE TITLE
Slack process remains in background after closing the app

### ISSUE THREAD

**Issue by bertogg** [flathub/com.slack.Slack#114]
Hi,

I noticed that if I run Slack and then quit the app (File -> Quit) the Slack process remains in the background:

```
21443 tty2     S+     0:00 bwrap --args 36 slack
21452 tty2     S+     0:00  \_ /app/extra/lib/slack/chrome-sandbox /app/extra/lib/slack/slack --type=zygote
```

If I do it several times I end up with many background processes. This also happens if I simply hide the window and then run Slack again to bring it to the foreground.

I'm using Slack 4.13.0, flatpak commit f72cdd2c40c9caf6fcf2835efb03c6f6c12836923fd67c7428d201f8dc9edac9, using flatpak 1.2.5 on Debian buster.

The exact same problem is happening with Skype, see https://github.com/flathub/com.skype.Client/issues/135

**Comment by AleksejShilin** [comment]
Seems to be fixed in 4.14.0.
