### ISSUE TITLE
Notification stick in Gnome and don't get removed

### ISSUE THREAD

**Issue by andypillip** [flathub/com.slack.Slack#119]
Unread messages appear in the Gnome notification tray, but when reading them in Slack, they don't disappear.

Gnome 40.0.0
Slack 4.14.0

I don't know if Gnome's DnD mode should be respected by Slack (set you on DnD inside Slack), since it doesn't (yet).

**Comment by ZVNexus** [comment]
This is an upstream issue with Slack, the same happens on Windows when I checked. Closing as there is nothing to do from the Flatpak side.

**Comment by lcarva** [comment]
For anyone coming across this issue, the [Junk Notification Cleaner](https://extensions.gnome.org/extension/8230/junk-notification-cleaner/) gnome extension is a reasonable workaround.
