### ISSUE TITLE
apt issue: 402 Payment Required

### ISSUE THREAD

**Issue by nrapopor** [flathub/com.slack.Slack#126]
Hi All,
Getting 
````bash
Err:17 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease                      
  402  Payment Required [IP: 54.183.216.24 443]
````
while running apt update

Thanks

**Comment by zeroepoch** [comment]
This repo is about the flatpak slack package. You should contact packagecloud.io about that issue. There is not apt update involved in running or install flatpak packages.
