### ISSUE TITLE
Mouse pointers have changed

### ISSUE THREAD

**Issue by edent** [flathub/com.slack.Slack#129]
Upgraded to the latest version, and my mouse pointer icons have changed - but only when in Slack.

I can't take a screenshot which includes pointers, unfortunately.  But they're now much smaller and completely different from my system theme.

* Ubuntu / Pop!_OS 20.10. Wayland.  
* Slack 4.17.2 64-bit

**Comment by edent** [comment]
Here are some examples of what my cursors usually look like, and how they look in Slack:
### Arrow
![gnome arrow](https://user-images.githubusercontent.com/837136/123778050-a5b39280-d8c8-11eb-95bb-137f7dd8871b.png)
![Slack arrow](https://user-images.githubusercontent.com/837136/123778053-a64c2900-d8c8-11eb-9516-ba1f7e395e9f.png)

### Pointer
![gnome pointer](https://user-images.githubusercontent.com/837136/123778060-a6e4bf80-d8c8-11eb-8686-6e3a4cd96405.png)
![slack pointer](https://user-images.githubusercontent.com/837136/123778056-a64c2900-d8c8-11eb-9a3f-d87f124be2c0.png)

### Text
![gnome text](https://user-images.githubusercontent.com/837136/123778063-a77d5600-d8c8-11eb-862d-d2f35fa73188.png)
![slack text](https://user-images.githubusercontent.com/837136/123778065-a77d5600-d8c8-11eb-8a43-604cba30b3e3.png)

This isn't happening on any of my other Flatpaks as far as I can tell.

**Comment by strikekat** [comment]
I have this issue as well with Fedora 34 and Gnome 40.1. It appears to use the default X11 cursor which doesn't scale to 1.5x like my normal cursor.
Additionally (and possibly related) my audio output completely stopped working, with no output device selectable besides "default".

I reverted for the moment per [the comment](https://github.com/flathub/com.slack.Slack/issues/125#issuecomment-869909585) in this other issue and Slack works normally again.

**Comment by edent** [comment]
Latest version has fixed it, thanks.

**Comment by oryband** [comment]
Issue has resurfaced on Ubuntu 22.04

**Comment by tunix** [comment]
Same here. Started to have this issue on Fedora Silverblue 38.
