### ISSUE TITLE
Missing Japanese Fonts?

### ISSUE THREAD

**Issue by jcaesar** [flathub/com.slack.Slack#14]
Japanese characters are rendered as boxes within app.
Testing string: 文字化けは嫌いけど、コレはｓｈｉｆｔ−ｊｉｓの問題ではない。

**Comment by simontol** [comment]
I can confirm this on org.telegram.desktop.
Look at the screenshot, on the left Telegram from rpmfusion on the right Telegram from flatpak.
![Screenshot_20190309_130059](https://user-images.githubusercontent.com/32391/54071372-09cf6a00-426c-11e9-94be-723f7f99cb99.png)

I can't reproduce the issue on Rocket.chat(from flatpak) that correctly diplays japanese characters.

**Comment by FakeShemp** [comment]
I'm closing this as it seems to have been solved in subsequent updates.
