### ISSUE TITLE
X-checker-data PRs broken likely due to Slack webpage change

### ISSUE THREAD

**Issue by vchernin** [flathub/com.slack.Slack#141]
Slack has released 4.18, but flathubbot hasn't opened a PR for it yet.

I assume it's due to x-checker-data no longer reflecting the [slack website](https://slack.com/intl/en-nl/downloads/instructions/ubuntu).

For now maybe a quick manual update should be done.

Potentially caused: https://github.com/flathub/com.slack.Slack/issues/140

**Comment by fcrozat** [comment]
Can be closed, flathubbot did its job some hours ago
