### ISSUE TITLE
Redundant app-created dialog when screen sharing on Wayland

### ISSUE THREAD

**Issue by vchernin** [flathub/com.slack.Slack#144]
PipeWire for screen sharing is enabled by default now on Wayland, see #139.

However from my past experience (and other Electron apps) Slack shows an unecessary dialog when screen sharing on Wayland. So I reported it here:
https://github.com/electron/electron/issues/30652

@WhyNotHugo can you confirm this Electron issue is also valid for Slack?

I am pretty confident I ran into it before, [I noted it here](https://github.com/flathub/com.slack.Slack/pull/118#issue-630002202).

**Comment by evan-a-a** [comment]
This isn't something we can fix in the flatpak.
