### ISSUE TITLE
Drop --filesystem=xdg-run/pipewire-0 from manifest

### ISSUE THREAD

**Issue by rmader** [flathub/com.slack.Slack#147]
The fact that screen sharing required Pipewire socked access despite using the xdg portal was a [WebRTC bug](https://webrtc-review.googlesource.com/c/src/+/230803). Once the fix has reached stable, `--filesystem=xdg-run/pipewire-0` can be dropped.

**Comment by WhyNotHugo** [comment]
We'll need to wait for Electron to release a stable version with this, and then Slack update their binary release.

**Comment by rmader** [comment]
AFAIK the fix went into Chromium 96, which again is the base for [Electron 16](https://www.electronjs.org/releases/stable?page=2#stack-upgrades-1600) from last November. Unfortunately [Slack release notes](https://slack.com/release-notes/linux) don't contain Electron updates (they did - but I assume they are not on Electron 4.2.1 any more...). So it *could* be that this already works now, but needs testing.

**Comment by razzeee** [comment]
They seem to list versions at https://app.slack.com/libs/desktop now, and they are still at electron 15

**Comment by ZVNexus** [comment]
@razzeee Yeah they just don't update that page anymore, the current Electron version is v28.1.2 when looking inside the asar package, which released last week (https://github.com/electron/electron/releases/tag/v28.1.2). Nice to see they're keeping it up to date.
