### ISSUE TITLE
Slack is no longer listed in the flathub repo

### ISSUE THREAD

**Issue by mzabaluev** [flathub/com.slack.Slack#151]
Slack seems to have been removed from the flathub repository:

```
error: Nothing matches com.slack.Slack in remote flathub
```

**Comment by cho2** [comment]
![Cuplikan layar dari 2021-11-15 08-37-16](https://user-images.githubusercontent.com/6271071/141709026-d1943e08-217c-4719-b5fb-e802e0ed37b3.png)

**Comment by mzabaluev** [comment]
Oh, I've just discovered that Fedora has applied a filter to their pre-configured Flathub repo.

**Comment by WhyNotHugo** [comment]
Fedora has a checkbox to allow proprietary software during installation. Did you check it?

**Comment by mzabaluev** [comment]
> Fedora has a checkbox to allow proprietary software during installation. Did you check it?

I did (I was able to install Chrome and other proprietary stuff), the filter [is not affected by this](https://pagure.io/fedora-flathub-filter). The workaround is to explicitly install the flathub repo.

**Comment by chelming** [comment]
Following up on this,

running `flatpak remotes` on a fresh Fedora 35 install results in
```
Name     Options
fedora  system,oci
flathub system,filtered
```

Running `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` will remove the filter.
