### ISSUE TITLE
Login with Firefox 94.0.2 does not work

### ISSUE THREAD

**Issue by Wuestenschiff** [flathub/com.slack.Slack#156]
Slack app will just stay on landing page. Works with Chromium

Slack / Flatpak Version:  4.22.0 64-bit

**Comment by razzeee** [comment]
I just installed the flatpak and it seemed to work fine with firefox 95

**Comment by Wuestenschiff** [comment]
As I can't test this anymore let's close this and hope it is fixed with current firefox
