### ISSUE TITLE
Gnome notification

### ISSUE THREAD

**Issue by kisst** [flathub/com.slack.Slack#16]
In locked screen the notifications from Slack shows up as `Electron` with a generic light-blob icon, instead of the Slack's own icon.

**Comment by TingPing** [comment]
Since its proprietary I'm not sure we can easily solve any incorrect info in notifications.

**Comment by kisst** [comment]
I'm pretty new to flatpak but as far as I can tell the flatpak is built out of the deb package, and if I install the deb directly then I get the right notifications, so that's why I raised it here as it seams to be packaging specific bug.

**Comment by nedrichards** [comment]
Which version of the Slack deb are you using? I see that they've [released a 3.2 beta 2](https://slack.com/release-notes/linux)  which appears to have updated their version of Electron to the 2.0 GTK3 branch. It may well be that this improves this as well. Otherwise, yes, you're right - this is something we should look at.

**Comment by kisst** [comment]
Same as in the [flatpack config](https://github.com/flathub/com.slack.Slack/blob/master/com.slack.Slack.json#L73)   `3.1.1` I just witched to flatpack due to [this bug](https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294) and till now it worked just fine.

**Comment by nedrichards** [comment]
I've upgraded to the latest version anyway in https://github.com/flathub/com.slack.Slack/commit/41e534adae16e00ba13bb58b31518bd1efaaa7a5 I don't expect it to fix the issue, but do let me know if it does.

**Comment by kisst** [comment]
That was quick !
I'm impressed ! 
However only partial success, the name of the notification is now correct but the logo is missing, however this 3.2 beta version I have not tested, with system install so might be broken there as well, I have to test that. Will get back on that.

**Comment by nedrichards** [comment]
Yeah, fwiw there's a bunch of notification fixes in the latest electron (which they're now based on) https://github.com/electron/electron/releases/tag/v2.0.0 that look like they'd make stuff more likely to work inside flatpak (which is strict about what it lets apps export)

**Comment by TingPing** [comment]
Flatpak changes both the icon name and the desktop file. So if it sets those in notifications yea they will be wrong.

**Comment by TingPing** [comment]
@nedrichards BTW I think it makes sense to just add NSS to the electron base app now. Seems like they all need it.

**Comment by kisst** [comment]
Installed the 3.2 beta on OS level, and now can confirm that both the logo and the text are correct there, only the flatpak version has the missing logo bug.

**Comment by nedrichards** [comment]
Right, I think this is going to be inevitable given the assets that flatpak lets you export from your container and the assets that the notification code is asking for. The only way to change this would be in the Slack code itself, and that's not something we control.
