### ISSUE TITLE
"Launch on login" does not work

### ISSUE THREAD

**Issue by pgalbraith** [flathub/com.slack.Slack#170]
The "launch on login" option can be selected, but it does not work.  Upon logging in the app does not start, and upon starting the app again the setting for launch on login has been lost.

**Comment by FakeShemp** [comment]
Are you using the flatpak version? This option cannot work on the flatpak version.

**Comment by WhyNotHugo** [comment]
Slack would need to ship a systemd unit for this to work, but it cannot do this via flatpak: https://github.com/flatpak/flatpak/issues/2787

FWIW, this doesn't work on non-flatpak versions either, due to the lack of a standard mechanism that would work on Linux desktop in general. Some DEs use autostart desktop entries, while many services rely on systemd's user units.

Just configure this via your DE settings (or your init script). Slack should probably remove the checkbox entirely and let users configure it via their desktop anyway.

**Comment by pgalbraith** [comment]
@WhyNotHugo this works fine on my desktop if I install the deb from the slack website.  While you may not like they way they wrote their app, and you may have very justifiable reasons for that opinion, I don't see how that translates into a supportable position that their implementation is defective and you can arbitrarily change the functionality you don't like and still label it as the same application.

**Comment by WhyNotHugo** [comment]
Like I said, there's no single standard way to implement "auto start on login" on Linux desktop. Whatever mechanism Slack's deb implements is also supported by your desktop, but it's no supported by Flatpak.

We can agree to disagree on opinions on the topic, but there's nothing that can be done for this package.You need to ask the guys over at https://github.com/flatpak/flatpak to implement a way for applications to auto-start. Like https://github.com/flatpak/flatpak/issues/2787

**Comment by pgalbraith** [comment]
@WhyNotHugo when there's a functionality issue that's blocked by an upstream issue, the usual way to handle that is to acknowledge the problem with a flagged issue, and refer to the upstream changes that are needed to fix the problem.  Simply denying that there's a problem doesn't help anyone.

**Comment by pgalbraith** [comment]
I'm definitely getting the impression that there's some nefarious practices going on somewhere, this is not the first flatpak app I've had issues with, nor the first where a dev has tried to pretend that a difficult-to-fix problem must not be a problem at all.  All this pretending that there aren't issues with flatpak apps is really painting a bad picture of the whole thing.

**Comment by FakeShemp** [comment]
We're not saying it's not an issue. We're saying it's an issue that is literally impossible to fix.

**Comment by pgalbraith** [comment]
If you acknowledge that this is functionality that works in the upstream app, and does not work in this package, then it's a packaging issue that should be acknowledged _formally_ by documenting it here and pointing out that it is _difficult_ to fix because it requires upstream work and collaboration, as @WhyNotHugo has already pointed out.  It is _not_ impossible, it's just _difficult_.

Closing this issue very loudly says that you don't believe it's an issue, and that attitude speaks very poorly of this entire project.  If the upstream developers realized that there were 150 issues caused that required this upstream functionality, don't you think that's important information?  Closing this issue is dishonest, and unhelpful.

**Comment by FakeShemp** [comment]
You are correct. I don't believe this is an issue. I believe you are the issue. 

Feel free to be the one taking over maintaining this Slack package cause I sure don't want to do it any more.

**Comment by pgalbraith** [comment]
Then you probably shouldn't be doing it.

**Comment by GerardoGR** [comment]
Sorry for Necro-bumping this issue. But I stumbled upon this issue looking for an answer and the solution I found might work for someone else:
Create a `com.slack.Slack.desktop` file under the `autostart` directory:
* From the terminal
```
cat <<EOF > ~/.config/autostart/com.slack.Slack.desktop
[Desktop Entry]
Categories=GNOME;GTK;Network;InstantMessaging;
Comment[en_US]=Slack Desktop
Comment=Slack Desktop
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=slack --file-forwarding com.slack.Slack @@u %U @@ --startup
GenericName[en_US]=Slack Client for Linux
GenericName=Slack Client for Linux
Icon=com.slack.Slack
MimeType=
Name[en_US]=Slack
Name=Slack
Path=
StartupNotify=true
StartupWMClass=Slack
Terminal=false
TerminalOptions=
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=
X-Desktop-File-Install-Version=0.26
X-Flatpak=com.slack.Slack
X-Flatpak-RenamedFrom=slack.desktop;
X-KDE-SubstituteUID=false
X-KDE-Username=
EOF
```
* Via KDE Plasma `5.25` UI: Go to _System settings_ -> _Startup and Shutdown_ -> _Autostart_ then click _Add_ -> _Add application_ -> Look for `slack` in the menu -> _Ok_ . It is worth to point out that if the `com.slack.Slack.desktop` is created this way the application will be started in a maximized window, if you want to start it hidden/minimized you need to add the `--startup` option as written in the terminal case.

**Comment by cataluna84** [comment]
Folks, you can set FlatPak application to run on startup via **Gnome Tweaks**. If you haven't already installed Gnome tweaks then run

`sudo apt install gnome-tweaks`

Launch Gnome Tweaks from applications and navigate to "Startup Applications"

![image](https://github.com/user-attachments/assets/fa71e10b-143e-462f-9eb6-afa844e785fd)

The flatPak applications are easily found from here.

**Comment by constgen** [comment]
flatpak Telegram can be added to autostart from its internal settings without a problem. So who sad this is "literally impossible" @FakeShemp ?
