### ISSUE TITLE
Input lag when typing

### ISSUE THREAD

**Issue by herlon214** [flathub/com.slack.Slack#171]
I installed the version `4.26.1` from Flathub and have seen a huge input lag when typing. The browser version and official .rpm are working fine.

I checked the Slack Spell Checker and disabled it. No change, still huge input lag when typing.

I am running Fedora 36 with Wayland.

**Comment by sebp** [comment]
Seems to related to electron not working nicely with Wayland. The lag disappears for me when running `flatpak run --socket=wayland com.slack.Slack --ozone-platform=wayland`, but then the window has no title bar, see https://github.com/electron/electron/issues/27016, https://github.com/electron/electron/issues/11907

**Comment by dottorblaster** [comment]
I'm experiencing this as well, starting the app with the correct ozone platform solves the issue but as @sebp says, no titlebar after that.

**Comment by evan-a-a** [comment]
Closing due to age.

**Comment by spacemoose** [comment]
The ticket is indeed old, but the problem persists, and drives me nuts.  I used to workaround it by disabling wayland on gnome, but now other software has trouble working with xorg, so that becomes less of an option.  I would love to see someone solve this.

**Comment by ZVNexus** [comment]
@spacemoose Do you have a NVIDIA GPU, and are you using the proprietary NVIDIA driver?

**Comment by insane-dreamer** [comment]
I'm experiencing this on Ubuntu 24.04 with Gnome; running Slack with Wayland disabled seems to fix it, but this is certainly still a bug. I have an nVidia GPU (Geforce 1650) with nvidia driver.
