### ISSUE TITLE
No window decorations/borders when running in Wayland

### ISSUE THREAD

**Issue by patriziobruno** [flathub/com.slack.Slack#184]
Wayland support works great with enhanced font and graphics rendering. Unfortunately, there are no borders to resize the window or drag-area to move the window around.

I'm on Fedora Silverblue 36, GNOME 42.

**Comment by NasrHassanein** [comment]
I'm having the same issue

Fedora 37, GNOME 43.2

**Comment by spockfish** [comment]
That's because it is missing the following command-line parameter:

`--enable-features=WaylandWindowDecorations
`

**Comment by patriziobruno** [comment]
> That's because it is missing the following command-line parameter:
> 
> `--enable-features=WaylandWindowDecorations `

This works, but it enables Mutter's titlebar. It seems Slack doesn't implement CSD on Linux.

**Comment by kaimast** [comment]
Seems like [this pull request](https://github.com/flathub/com.slack.Slack/pull/213/files#diff-57d153662854f39c1f3739856905c814bea354be62e7c4c7b32f34fe56ab1ebeL58) disabled the `WaylandWindowDecorations` feature flag, so even if you force Wayland through Flatseal (by removing permissions for X11) the window decorations are missing.

Maybe it could be re-enabled, even if Wayland is not used by default? Wayland window decorations worked fine for me before that change and this feature should not break anything related to X11 afaik.

**Comment by b1zzu** [comment]
Hi, I'm having the same issue, and I've tried to run Slack like this

```
flatpak run com.slack.Slack --enable-features=WaylandWindowDecorations
```

but the result is the same, slack start and runs but can reseize the window.

Is it because the arg is not pick from slack or because it simply it's a slack bug that can be solved with it?

**Comment by ZVNexus** [comment]
Hmmm I have window decorations when running under Wayland natively:

![image](https://github.com/user-attachments/assets/fcd7947e-8ed2-450e-a755-e1557b9bc408)

I assume you switched to Wayland with the below right?
`flatpak override --user --socket=wayland com.slack.Slack`

**Comment by patriziobruno** [comment]
> Hmmm I have window decorations when running under Wayland natively:
> 
> ![image](https://private-user-images.githubusercontent.com/19439046/384898703-fcd7947e-8ed2-450e-a755-e1557b9bc408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjQ4NzIsIm5iZiI6MTczMTMyNDU3MiwicGF0aCI6Ii8xOTQzOTA0Ni8zODQ4OTg3MDMtZmNkNzk0N2UtOGVkMi00NTBlLWE3NTUtZTE1NTdiOWJjNDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllN2NkODgzNjVhMzk1OTE0N2MyNzg2YTg4OWI4ZDJlMzczMDE4YmJmYTY3MDVkMDQzNTM5NjAyYTdkNmM4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n_maYFhls0-R5dwd179FvHPsmAitE682b1q5NC60nQw)
> 
> I assume you switched to Wayland with the below right? `flatpak override --user --socket=wayland com.slack.Slack`

The decorations you see are rendered by Mutter, not Slack. Meaning that Slack doesn't implement CSD the way VSCode (an Electron app just like Slack) does. Slack implements CSD correctly on Mac and Windows, not on Linux.

**Comment by ZVNexus** [comment]
> The decorations you see are rendered by Mutter, not Slack. Meaning that Slack doesn't implement CSD the way VSCode (an Electron app just like Slack) does. Slack implements CSD correctly on Mac and Windows, not on Linux.

Unless something has changed, Mutter doesn't support server side decorations on Wayland, only for XWayland clients. On GNOME (Wayland) the decorations are drawn by Electron I believe.
