### ISSUE TITLE
Message Timestamps in wrong timezone.

### ISSUE THREAD

**Issue by kaiwalyajoshi** [flathub/com.slack.Slack#187]
I'm seeing #43 re-appear in Slack version `4.28.184` running on Fedora 37.

I've fixed the issue locally using the [comment](https://github.com/flathub/com.slack.Slack/issues/43#issuecomment-530164518)
```
flatpak override --user --env=TZ=America/Los_Angeles com.slack.Slack
```

The bug appears to be within the client itself, setting the correct timezone from workspace settings does not fix the issue.

**Comment by evan-a-a** [comment]
Closing due to age and the fact that this is not something that Flatpak package can fix.
