### ISSUE TITLE
App needs access to `D-Bus session bus`

### ISSUE THREAD

**Issue by gtirloni** [flathub/com.slack.Slack#193]
On GNOME 44, the Slack icon stopped showing in the tray (using AppIndicator or Tray-Icons-Reloaded extensions).

The way to get that working again is by granting it access to `socket-session-bus` (e.g., in FlatSeal).

Could this permission be added by default to this flatpak?

**Comment by mvdan** [comment]
After giving it access, I notice that Slack now creates and uses a "Chromium safe storage" secret in my keyring. Perfectly fine for me, just slightly surprising.

**Comment by evan-a-a** [comment]
This should be fixed by #213
