### ISSUE TITLE
Slack crashes in fedora 38

### ISSUE THREAD

**Issue by jsnjack** [flathub/com.slack.Slack#194]
After updating to fedora 38, Slack application installed via flathub has started to crash. I'm currently on version 4.31.155.  Steps to reproduce:
1. Clean  Slack local directory `rm --rf /home/$USER/.var/app/com.slack.Slack`
2. Start Slack, log in
3. Close Slack
4. Start Slack again. It will load messages and crash after few seconds. Couldn't find anything interesting in logs. It looks like it exists immediately after the message `All files fetched and put in cache 867.9000000059605ms `

**Comment by adandreou** [comment]
I had the same issue and I resolved it by resetting the application's permissions, using Flatseal. Maybe this will help you as well.

**Comment by andreasfernandez** [comment]
Thanks a lot, @adandreou. Resetting permissions seems to solve the issue for me.

**Comment by jsnjack** [comment]
Many thanks, Andreas! Worked for me too

**Comment by artificial-intelligence** [comment]
I have a related issue on fedora 37, where it only crashes if using the video features

**Comment by adandreou** [comment]
> I have a related issue on fedora 37, where it only crashes if using the video features

Yeah, I have the same issue when screen sharing. I tested it using the instructions here:

**Comment by artificial-intelligence** [comment]
> > I have a related issue on fedora 37, where it only crashes if using the video features
> 
> Yeah, I have the same issue when screen sharing. I tested it using the instructions [here](https://slack.com/help/articles/115003538426-Troubleshoot-audio-and-video-issues-in-Slack)

well it even crashes during the test, but not at the camera, that part works fine, only when it comes to screen sharing the complete app crashes, as reported here (backtrace attached):

https://github.com/flathub/com.slack.Slack/issues/195

**Comment by mooey5775** [comment]
Seems to me that enabling "Run in Background" in GNOME's app settings is the key for Slack to run. I'm not sure why this is required, as Slack runs fine without it enabled in Fedora 37. Maybe it's related to https://github.com/flatpak/xdg-desktop-portal/issues/899?

**Comment by rmsync** [comment]
> I had the same issue and I resolved it by resetting the application's permissions, using Flatseal. Maybe this will help you as well.

This worked for me. Thank you!

**Comment by evan-a-a** [comment]
Related to #101
