### ISSUE TITLE
slack crashes on fedora 37 when using the share screen functionality or when recording video

### ISSUE THREAD

**Issue by artificial-intelligence** [flathub/com.slack.Slack#195]
Hi,

see $subject.

Here is the backtrace as reported by `abrt-cli backtrace $id`

[slack_backtrace.txt](https://github.com/flathub/com.slack.Slack/files/11294679/slack_backtrace.txt)

**Comment by chome-codebranch** [comment]
I had the same issue on Fedora 37.

**Comment by chsjr1996** [comment]
Same problem here, I needed to downgrade Slack from "4.31.**155**" to "4.29.**149**" to make screen share works again.

OBS: I use Slack flatpak version, and run this command to downgrade to previous commit:
`sudo flatpak update --commit=b95d24a8a354db07b95b065b3e57e9442c9fbaf851a49cbe6e7b1aa0afcab591 com.slack.Slack`

**Comment by friimaind** [comment]
Same problem here

Arch on EndeavourOS 2021.11.30 - Gnome 44.1 Wayland

**Comment by RigottiG** [comment]
Same problem here on Manjaro 22 using wayland

**Comment by RobbertDM** [comment]
Same here on slack 4.33.84, ubuntu 22.04 (linux kernel 6.2.0-26-generic), gnome 42.9

**Comment by Bartwillemsen** [comment]
The newest version released recently (4.34.115) fixes the issue for me here. It's not listed on the download page yet, but you can download it by navigating to the following page: https://downloads.slack-edge.com/releases/linux/4.34.115/prod/x64/slack-4.34.115-0.1.el8.x86_64.rpm

**Comment by DasJott** [comment]
Installed as Flatpak on Fedora 38, running Version 4.34.120
Crashes as soon as I click on "Share Screen".
Also I experienced an overall blurry UI, including the window title. Fixed that with disabling Wayland using Flatseal.
However that didn't fix the screen share problem.

**Comment by evan-a-a** [comment]
Related to #101
