### ISSUE TITLE
Update to 4.31.155 break tray icon in Debian 11 running wayland

### ISSUE THREAD

**Issue by tgm-git** [flathub/com.slack.Slack#198]
The older version 4.29.149 works fine. I found the following error in the logs:

```
[2:0501/151013.326793:ERROR:bus.cc(562)] Failed to get the ownership of org.kde.StatusNotifierItem-2-1: org.freedesktop.DBus.Error.ServiceUnknown
```
Via Flatseal I gave Slack access to dbus, but the error persisted in logs and the tray icon did not appear again. Current workaround is to rollback to version 4.29.149

**Comment by evan-a-a** [comment]
Believe this to be fixed per PR.

**Comment by tgm-git** [comment]
I can confirm it works as of `4.36.138`
