### ISSUE TITLE
Blurry tray icon

### ISSUE THREAD

**Issue by LinAGKar** [flathub/com.slack.Slack#199]
Lately, the tray icon of the Slack flatpak has been really blurry. Compare below the snap version on the left and the flatpak version on the right.

![slack icon](https://user-images.githubusercontent.com/3390621/235708007-dc0a679b-431e-4f34-9acf-76f96ff719f9.png)

It also seems like the flatpak uses xembed, while the snap version probably uses SNI.

This is on OpenSUSE Plasma. I see it on both Leap 15.4 and Tumbleweed.

**Comment by roworu** [comment]
I was able to fix mine by enabling D-Bus session in Flatseal:
![image](https://github.com/flathub/com.slack.Slack/assets/36964755/53321f4d-1e98-4f0e-b79d-57987299946c)

**Comment by ZVNexus** [comment]
FYI, testing on KDE Plasma 6 does not have a blurry tray icon.

![image](https://github.com/flathub/com.slack.Slack/assets/19439046/83bf2567-4cd4-4160-b104-88b67d1f6edd)

**Comment by ZVNexus** [comment]
@LinAGKar When KDE 6 releases next month, can you verify that it's been fixed with default permissions?

**Comment by LinAGKar** [comment]
Don't know when I'll get Plasma 6, but I'll test it once I do

**Comment by ZVNexus** [comment]
Note, went to KDE Plasma 5.27.10 (Fedora 39), and it's not blurry here either. @LinAGKar Can you test this with the latest version?

**Comment by LinAGKar** [comment]
Yes, tried reinstalling Slack so it would get the default permissions, and it does indeed get the correct tray icon on Plasma 5.27.10.
