### ISSUE TITLE
Dbus errors, fixed when enabling socket=system-bus

### ISSUE THREAD

**Issue by brittyazel** [flathub/com.slack.Slack#202]
Right now, when launching Slack I am getting a multitude of dbus errors:

`[2:0602/111324.324733:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

These errors seem to be resolved when enabling socket=system-bus in Flatseal. Would you consider enabling that in the manifest by default? Is there a reason to not allow access to the dbus system bus?

**Comment by milkknife** [comment]
https://docs.flatpak.org/en/latest/sandbox-permissions.html#d-bus-access
>Access to the entire bus with --socket=system-bus or --socket=session-bus should be avoided, unless the application is a development tool.

If I'm not mistaken, enabling system bus permission effectively disables the sandbox. It's only meant for briefly testing things.

**Comment by bhack** [comment]
Is it still an issue with https://github.com/flathub/com.slack.Slack/pull/205 ?

**Comment by milkknife** [comment]
I'm not able to test it, but I'm certain an issue with the root cause being misconfigured sandbox permissions has nothing to do with updating the .deb itself. The kind of error OP mentioned happens when a certain `--talk-name` permission is not set in the manifest.
