### ISSUE TITLE
Bump to 4.32.127

### ISSUE THREAD

**Issue by JGMelon22** [flathub/com.slack.Slack#204]
Any chances to update the package to the newest release?
https://slack.com/release-notes/linux

**Comment by bhack** [comment]
https://github.com/flathub/com.slack.Slack/pull/203

Is this project currently maintained?

**Comment by cho2** [comment]
> Is this project currently maintained?

Yes, the updates are handled by flathubbot, it creates pull request automatically, but it needs to merge manually.
Perhaps, need another maintainer to merge?
cc @FakeShemp  @barthalion
