### ISSUE TITLE
Input Method Issues when using --enable-wayland-ime

### ISSUE THREAD

**Issue by kassick** [flathub/com.slack.Slack#211]
After commit a8ceac4d3121109adfe9344568b95e523db1c09b included the `--enable-wayland-ime` option, running Slack under a a Gnome session for Brazilian Portuguese (`LANG=pt_BR.utf-8`), composing `'` and `c` in a `us-intl` layout produces `ć` (not used in Portuguese) instead of the expected `ç` (cedilla)

*How to Reproduce*

1. Install/update the Slack Flatpak in an environment configured for Brazilian Portuguese
2. With the keyboard configured to use `us-intl` layout, press `'` followed by `c`

*Expected Result*

`ç` is inserted in the text entry, as with every other app under wayland or Xwayland, flatpak or not.

*Observed Result*

`ć` is inserted in the text entry

**Comment by kassick** [comment]
Maybe Relevant: Using Slack with on commit a8ceac4d, `ibus` shortcuts to open the emoji popup or insert arbitrary unicode characters by hex code no longer work (as it does in other apps). After rolling back to 8d3afba9, I can confirm that the emoji popup and unicode hex code shortcuts work in Slack -- therefore, slack is using iBus as IME, as are the apps outside of flatpak

**Comment by evan-a-a** [comment]
This should be fixed by #213
