### ISSUE TITLE
arm64 version

### ISSUE THREAD

**Issue by andirsun** [flathub/com.slack.Slack#228]
Hey! I am using fedora on my macbook pro m1 running asahi linux project https://fedora-asahi-remix.org/
Our architecture is arm64 but slack is not available to install, electron supports arm64 so would be possible to add the support ?

**Comment by andirsun** [comment]
Thanks for the info. I am planing to create my own flatpak with arm64 version of Slack.

**Comment by evan-a-a** [comment]
Nothing I can find indicates that Slack is distributing an ARM64 Linux client yet, so I don't think there's anything for us to do at the moment. If Slack starts distributing an arm64 client in the future then I'll be sure to add support for it in the flatpak.

**Comment by hamza72x** [comment]
here we go: https://github.com/hamza72x/slack-linux-arm64

**Comment by andirsun** [comment]
https://github.com/andirsun/Slacky
