### ISSUE TITLE
Cannot access webcam for video calls

### ISSUE THREAD

**Issue by j0ni** [flathub/com.slack.Slack#23]
I'm not sure if this is a thing I can configure locally, but I'm new to flatpak and haven't figured it out yet if so.

When I join slack calls, I can use my microphone, but the video icon is greyed out and the camera configuration pulldown says "no cameras found". I suspect the build needs something like `--device=all` (see [this section of the manual](http://docs.flatpak.org/en/latest/sandbox-permissions.html#device-access)).

**Comment by j0ni** [comment]
Update: I read a bit more, and built a fresh flatpak from this repo, with `--device=dri` changed to `--device=all` and it had the desired effect. I'm not sure what the other consequences may be of this change, so I have not done a PR yet. LMK.

I also noticed that during calls, slack is not preventing my inactivity timeout from running down, so I have to keep hitting the keyboard when the screen starts to dim for locking. I'm not sure yet how to fix that, but FYI.

**Comment by TingPing** [comment]
> I also noticed that during calls, slack is not preventing my inactivity timeout from running down, so I have to keep hitting the keyboard when the screen starts to dim for locking. I'm not sure yet how to fix that, but FYI.

It probably does that over dbus, you can do `flatpak run --log-session-bus com.slack.Slack` go see if anything is being blocked.
