### ISSUE TITLE
Slack requires signing in every launch

### ISSUE THREAD

**Issue by mattmilano** [flathub/com.slack.Slack#260]
On multiple computers running LMDE, Slack requires signing back in to all workspaces after the update to 4.37.77.

After logging back in and closing the app, it requires signing back in on every subsequent launch.

Resetting app data, cache, etc does not fix the issue.

**Comment by ZVNexus** [comment]
@mattmilano Test this build and let me know if the issue persists:

flatpak install --user https://dl.flathub.org/build-repo/82386/com.slack.Slack.flatpakref

**Comment by revelation1** [comment]
Installed the test build but still broken.  Quit slack and reload and it shows a brief error message before requiring browser login again.

**Comment by ZVNexus** [comment]
> Installed the test build but still broken. Quit slack and reload and it shows a brief error message before requiring browser login again.

The test build is a revert to 4.36.140, so this is likely unrelated to the client itself. Could you test the Slack RPM/DEB or snap? There's a chance Slack changed something on their backend.

**Comment by MrPancakes39** [comment]
Have same issue.

Distro: Pop!_OS 22.04 LTS
Kernel: 6.6.10
Slack version: 4.37.77

**Comment by revelation1** [comment]
Bit more troubleshooting. .. I noticed this only happens on one machine.  My other machine with a nearly identical silverblue install works fine.  

- Uninstalled the flatpak.
- Reinstalled the "system" flatpak.
- Signed in.

Problem appears solved.

**Comment by mattmilano** [comment]
I also checked the issue on an old Mac I have laying around. It works too. So it wouldn't seem to be an issue with Slack's servers.

**Comment by scrlkx** [comment]
Same issue here.

Although the RPM version is also broken so I assume that i snot related to Flatpak version.

**Comment by charn** [comment]
Distro: Fedora 39

Wasn't able to reproduce this issue on rpm which is on version 4.36.140
Also couldn't reproduce this with the flatpak running 4.36.140

So for the flatpak version the temporary fix now seems to be to downgrade:

```
flatpak update --commit=468a87491d4f342d8813232ebc511731648f55a69fe7ceb722b9225c2b34fbf3 com.slack.Slack
```

**Comment by revelation1** [comment]
Confirmed that downgrade fixes it.  also added this to keep it from updating again.

flatpak mask com.slack.Slack
