### ISSUE TITLE
Last version in flathub is bugged

### ISSUE THREAD

**Issue by VitorVRS** [flathub/com.slack.Slack#29]
Distro Manjaro Linux 18.02 (up to date)
Kernel: Linux vitor 4.19.13-1-MANJARO #1 SMP PREEMPT Sat Dec 29 15:43:56 UTC 2018 x86_64 GNU/Linux
Slack Version: Direct Download 3.3.7 64-bit

Channel details are missing icons and labels:
![screenshot from 2019-02-01 09-04-14](https://user-images.githubusercontent.com/3956573/52119398-1bd04400-2600-11e9-8812-0cf0b24c5b6b.png)

Clicking on user name/photo doesn't show their profile info.

**Comment by TingPing** [comment]
These all work here.
