### ISSUE TITLE
Unacceptable TLS certificate on Installation

### ISSUE THREAD

**Issue by jeteokeeffe** [flathub/com.slack.Slack#31]
flatpak install -v -y com.slack.Slack
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/jeterokeeffe/.local/share/flatpak
Looking for matches…
F: Fetching summary file for remote ‘flathub’
F: Fetching summary file for remote ‘flathub’
F: Transaction: install flathub:app/com.slack.Slack/x86_64/stable[*]
F: Updating remote metadata for flathub
F: marking op install:app/com.slack.Slack/x86_64/stable resolved to 804b4ac18190c41df1f4faebd37e5f35ac472a76e713e7674a198ee0d2a043fe
F: Updating dependent runtime runtime/org.freedesktop.Platform/x86_64/18.08
F: Transaction: update flathub:runtime/org.freedesktop.Platform/x86_64/18.08[$old]
F: marking op update:runtime/org.freedesktop.Platform/x86_64/18.08 resolved to 30d1e0e6f128912bc3e7075e7d55363e9ade59a72c0eac1c21cae237593a7aba
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.Locale/x86_64/18.08[/en]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08[*]
F: marking op install/update:runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08 resolved to 337041240b18dbd4fc70cfd84d45f0f8145d72bdda277639f45beadc52ec6afd
F: marking op install/update:runtime/org.freedesktop.Platform.Locale/x86_64/18.08 resolved to 3756db4fedc7e9f0cf629d978425369e90287fd82570915f1b969c0a7b7dc0e0

com.slack.Slack permissions:
    ipc	network	pulseaudio	x11
    devices	file access [1]	dbus access [2]

    [1] home, xdg-run/dconf, ~/.config/dconf:ro
    [2] ca.desrt.dconf, org.freedesktop.Notifications, org.kde.StatusNotifierWatcher

 1.	   	com.slack.Slack	x86_64	stable	flathub	< 57.8 MB

Installing… █▌                     8%  53.1 kB/sF: Loading https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.7-amd64.deb using libsoup
Error: While downloading https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.7-amd64.deb: Unacceptable TLS certificate
error: Failed to install com.slack.Slack: While downloading https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.7-amd64.deb: Unacceptable TLS certificate

curl -v https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.7-amd64.deb
*   Trying 146.112.61.106...
* TCP_NODELAY set
* Connected to downloads.slack-edge.com (146.112.61.106) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by vchernin** [comment]
Does this issue still occur today? It's been nearly 2 years since this bug was reported.

I have no issues installing slack using the command listed (`flatpak install -v -y com.slack.Slack`) today.

**Comment by markcellus** [comment]
Yes this is still an issue for me on Ubuntu

**Comment by evan-a-a** [comment]
Closing due to age and no actionable fixes for the flatpak.
