### ISSUE TITLE
Update to 3.4.0

### ISSUE THREAD

**Issue by tristan957** [flathub/com.slack.Slack#35]
I'd like to try my hand at providing a pull request to fix this. Is there any documentation for updating a flatpak through this repo?

**Comment by barthalion** [comment]
Looks like @cho2 filled one: https://github.com/flathub/com.slack.Slack/pull/36

You can clone git repo, do required changes, and then run `flatpak-builder --verbose --sandbox --force-clean --repo=repo --ccache --user --install-deps-from=flathub --default-branch=flathub --state-dir=/home/bp/.cache/flatpak-builder --install builddir com.slack.Slack.json` (the command is more or less what our CI uses). If it builds, installs and works fine, then it should be good to submit. Additionally `bot, build` triggers test build under pull request.

**Comment by tristan957** [comment]
@barthalion thanks. I'll be sure to write this down for the future!
