### ISSUE TITLE
Install .desktop file

### ISSUE THREAD

**Issue by marcosps** [flathub/com.slack.Slack#4]
Currently, after installing Slack from flathub, it's not being shown in the Cinnamon's menu, due to the lack of a .desktop file being installed.

Spotify (from flathub as well) already shows the right icon.

**Comment by TingPing** [comment]
It is installed and works as expected here.

Same question as flathub/com.skype.Client#3 basically, try restarting the session?

**Comment by marcosps** [comment]
Just to be sure, I reinstalled the same flatpak, and restarted the Cinnamon session, but it didn't worked as I said before.

**Comment by TingPing** [comment]
Just to verify it is installed: `find ~/.local/share/flatpak /var/lib/flatpak -name 'com.slack.Slack.desktop' -print`

**Comment by marcosps** [comment]
This command returns nothing:
find ~/.local/share/flatpak /var/lib/flatpak -name 'com.slack*' -print | wc -l
0

But, spotify does install the correct files:
find ~/.local/share/flatpak /var/lib/flatpak -name 'com.spotify*' -print | wc -l
27

**Comment by TingPing** [comment]
Hmm, what `flatpak` version?

**Comment by TingPing** [comment]
Also whats the output of `flatpak info com.slack.Slack`

**Comment by marcosps** [comment]
[marcos@Osiris ~]$ flatpak --version
Flatpak 0.9.12
[marcos@Osiris ~]$ flatpak info com.slack.Slack 
Ref: app/com.slack.Slack/x86_64/stable
ID: com.slack.Slack
Arch: x86_64
Branch: stable
Origin: flathub
Commit: 784929e4d6cc3925e5825b5021f664118cad4ffcd8da53431984937091cef47a
Location: /usr/local/var/lib/flatpak/app/com.slack.Slack/x86_64/stable/784929e4d6cc3925e5825b5021f664118cad4ffcd8da53431984937091cef47a
Installed size: 17.0 MB
Runtime: org.freedesktop.Platform/x86_64/1.6

**Comment by TingPing** [comment]
> /usr/local/var/lib/flatpak/app/com.slack.Slack/x86_64/stable/784929e4d6cc3925e5825b5021f664118cad4ffcd8da53431984937091cef47a

Oh well that explains why that `find` command didn't work and probably why your shell isn't picking it up. Seems like you built `flatpak` in a non-standard prefix that probably isn't in `XDG_DATA_DIRS`.

**Comment by marcosps** [comment]
Oops... sorry. Some months ago I compiled flatpak, and let the default prefix as it is. After reinstalling flatpak here, installing Slack from flathub and restart Cinnamon session, the icon appeared. Sorry for the noise.
