### ISSUE TITLE
Black screen during calls

### ISSUE THREAD

**Issue by DamienCassou** [flathub/com.slack.Slack#44]
Starting with 3.4.2, when I'm in a call with someone, clicking in the call window would make my screen turn mostly black:

![2019-06-05-091531_4480x1080_scrot](https://user-images.githubusercontent.com/217543/58937433-b7bab980-8772-11e9-825b-84e615b08f79.png)

This might be a problem with my [EXWM window manager](https://github.com/ch11ng/exwm) but this works fine in 3.4.0. More precisely,

```session
$ sudo flatpak --verbose update --commit=014b6644d7f75120a47e7edce86a875c81b4e27a1844bfcfafcfe6280bdfafd6 com.slack.Slack
```

does *not* work whereas

```session
$ sudo flatpak --verbose update --commit=810ae703189dd439c5a7059accf33af495d415e2d46545a3bfcccf445ab7c092 com.slack.Slack
```

does work.

```
KO  Commit: 014b6644d7f75120a47e7edce86a875c81b4e27a1844bfcfafcfe6280bdfafd6
   Subject: Update to 3.4.2 (3a013998)
      Date: 2019-06-02 07:17:13 +0000

OK  Commit: 810ae703189dd439c5a7059accf33af495d415e2d46545a3bfcccf445ab7c092
   Subject: Update to 3.4.0 (394c89bb)
      Date: 2019-05-08 07:42:39 +0000
```

**Comment by FakeShemp** [comment]
I'm not on a paid plan Slack which is required for making calls, so I'm not able to test.

**Comment by DamienCassou** [comment]
> I'm not on a paid plan Slack which is required for making calls, so I'm not able to test.

I'm willing to do testing as it's quite easy to reproduce for me. Please tell me if I can be of any help. I'm on #flatpak on IRC if you want, just ping DamienCassou.

**Comment by nedrichards** [comment]
You can make 1:1 Audio calls on free slack can't you?

**Comment by DamienCassou** [comment]
I still face the same issue.

**Comment by FakeShemp** [comment]
I'm not able to reproduce. A new window pops up with both audio and video, clicking does nothing to break it. Even the small thumb-like window works as it should.

**Comment by DamienCassou** [comment]
EXWM gave an explanation as to what is happening: https://github.com/ch11ng/exwm/issues/582#issuecomment-502463829
