### ISSUE TITLE
No sound without pulseaudio

### ISSUE THREAD

**Issue by j0ni** [flathub/com.slack.Slack#49]
I don't have pulseaudio running (I don't use gnome, and I need realtime audio for using pro audio apps), instead using alsa directly. With this configuration I cannot hear anything and my mic doesn't work.

I don't think it's a problem with slack per se, because I also have a standalone installation (via the Arch User Repo) which works fine with alsa alone.

Is there something I can configure to allow slack access to alsa devices?

Also, I think this would be a useful FAQ, even if it's just to say the flatpak Slack package requires pulseaudio - knowing that in advance would have saved me a bunch of time :)

**Comment by FakeShemp** [comment]
Doesn't all flatpaks require pulseaudio for sound?

**Comment by TingPing** [comment]
You can usually pass `--device=all` and direct ALSA hardware access works.

I don't think it should be added just for the niche case of purposefully avoiding pulseaudio.

**Comment by nedrichards** [comment]
Sandboxing audio is a core flatpak concern rather than for the app (and it's certainly something that's being worked on with PipeWire for non pulse use cases).
