### ISSUE TITLE
Downloaded files are nowhere to be found

### ISSUE THREAD

**Issue by fdcds** [flathub/com.slack.Slack#52]
1. An image was attached to a post in one of our channels.
2. I hover the mouse over it and click the then-appearing download icon.
3. A "Downloads" side-bar pops up, showing the name of the image file.
4. I hover over the image file name and click the then-appearing "open containing folder" text.
5. Nothing happens.
6. I click the image file name itself
7. Nothing happens.
8. I browse to the "Downloads" folder on my main system, i.e. not inside a flatpak app.
9. The image file is not present in the "Downloads" folder.
10. I also browse "Documents", "Pictures", $HOME and $HOME/.var/app/com.slack.Slack, but the image file is nowhere to be found.

**Comment by cho2** [comment]
- Slack Flatpak version?
- Flatpak version?
- OS?

> I hover over the image file name and click the then-appearing "open containing folder" text.

It goes to `/home/myHome/Downloads` folder on mine.
Slack 4.0.1 with Flatpak 1.2.3 on openSUSE Leap 15.1

**Comment by fdcds** [comment]
```
$ flatpak info com.slack.Slack

Slack - Chat with your team

          ID: com.slack.Slack
         Ref: app/com.slack.Slack/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.0.1
     License: LicenseRef-proprietary
      Origin: com.slack.Slack-origin
  Collection: org.flathub.Stable
Installation: system
   Installed: 2.8 MB
     Runtime: org.freedesktop.Platform/x86_64/18.08
         Sdk: org.freedesktop.Sdk/x86_64/18.08

      Commit: a10574ca28995af9d14a2510e369e458d47b0b35b78e80b7fae29995b607bd16
      Parent: dd864e4fc3d1eab1c29930e1f913bbc83c88cfdaa805a09e088b495563977703
     Subject: Update to 4.0.1 (bc4873db)
        Date: 2019-07-31 11:43:20 +0000
```

```
$ flatpak --version
Flatpak 1.4.2
```

```
$ grep PRETTY /etc/os-release
PRETTY_NAME="Fedora 30 (Thirty)"
```

**Comment by FakeShemp** [comment]
It should go to your `XDG_DOWNLOAD_DIR`. Have you changed it from the default?

**Comment by FakeShemp** [comment]
You can also change your download path manually under File > Preferences > Advanced

**Comment by fdcds** [comment]
> It should go to your `XDG_DOWNLOAD_DIR`. Have you changed it from the default?

That variable is not set, outside of the flatpak container at least.

> You can also change your download path manually under File > Preferences > Advanced

Thank you for the hint. That was the cause. I moved my home directory a while ago, and Slack's "Download Location" was still pointing at the old one, which probably meant that either (a) all writes to the Download Location failed and there was no error message or (b) everything was written to a directory hidden within the flatpak container.

Is it possible to make such writes fail in an obvious way?

**Comment by TingPing** [comment]
> Is it possible to make such writes fail in an obvious way?

Not really. The entire sandbox is a tmpfs basically except for its mounts so you can write anywhere inside of it successfully and the files exist in memory.

**Comment by insanemal** [comment]
> Not really. The entire sandbox is a tmpfs basically except for its mounts so you can write anywhere inside of it successfully and the files exist in memory.

Ok but I could not seem to see the tempfs mount location as a seperate mount point... Is there an easy way to figure out where it is? So then perhaps I can at least get files out...

**Comment by TingPing** [comment]
You can see them in `/proc/$PID/root`

**Comment by ieugen** [comment]
I'm on Debian 10 and I fixed the issue by going into the settings and changing the downloads path.

I'm using Romanian and my Downloads folder is `Descărcări`.
 `echo $XDG_DOWNLOAD_DIR ` is empty.

```
cat ~/.config/user-dirs.dirs 
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Descărcări"
XDG_TEMPLATES_DIR="$HOME/Șabloane"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documente"
XDG_MUSIC_DIR="$HOME/Muzică"
XDG_PICTURES_DIR="$HOME/Poze"
XDG_VIDEOS_DIR="$HOME/Video"
```
So it seems that Slack does not read the `XDG_DOWNLOAD_DIR` value in my case.

**Comment by mzabaluev** [comment]
When I enter the Slack sandbox with `sudo -E flatpak enter $INST sh`, the environment variable `XDG_DOWNLOAD_DIR` is not set in the shell while other XDG variables are. I assume this means the app is not aware of the correct location even if it honors the XDG variable.

**Comment by z3ntu** [comment]
I have made myself this shortcut for opening the file explorer to the correct directory: `open /proc/(pidof -s /app/extra/lib/slack/slack)/root/home/luca/Downloads`

**Comment by justdanyul** [comment]
I have similar problems on Arch Linux, and basically it was down to sandbox permissions. I had to issue `sudo flatpak override com.slack.Slack --filesystem=home`

**Comment by arielnmz** [comment]
So, the solution would be for slack to simply read `$HOME/.config/user-dirs.dirs `, right?

**Comment by ieugen** [comment]
I think Slack would need access to `$HOME/.config/user-dirs.dirs` . Don't know if it gets it by default.

**Comment by TingPing** [comment]
` $XDG_CONFIG_HOME/user-dirs.dirs` exists inside the sandbox.

**Comment by arielnmz** [comment]
> ` $XDG_CONFIG_HOME/user-dirs.dirs` exists inside the sandbox.

It exists, but it's empty (at least for me). And if it wasn't what's the point of having the XDG vars point to a dir inside the flatpak app context (`.var/app/com.slack.Slack`)? 

Btw just tried defining the variables before starting slack:

![image](https://user-images.githubusercontent.com/24735547/76255974-61e8d580-620c-11ea-8879-165be11eccc5.png)

But that didn't work either.

I even tried with my user's `user-dirs.dirs` by cp'ing it into slacks config

`cp .config/user-dirs.dirs .var/app/com.slack.Slack/config/`

But not even that works.

Any ideas?

**Comment by arielnmz** [comment]
Btw I think this goes deeper than just finding the Downloads dir since you can't upload files from your home because slack just can't find them, drag and drop doesn't work either but that may be a different thing.

**Comment by pablit07** [comment]
Also having this problem
Slack Version 4.3.3
255b573-s@1584473739 (App Store)
Thanks

**Comment by Tomicapo** [comment]
Still having this problem in windows. An "open containing folder" option is desperately needed.

**Comment by insanemal** [comment]
It's totally a permissions thing. It's just not requesting the permissions correctly. 
I have other apps in flatpack that overclock my GPU and they ask the right questions and get the right access

**Comment by bradenmcd** [comment]
This continues to be a problem when installing the 4.7.0 flatpak on Fedora 32:
- The "downloads" folder defaults to a location inside the sandbox; and the file selector that would be used to change it cannot see outside the sandbox.
- Attempting to share **any** file (from outside the sandbox) via drag-and-drop yields an "unsupported file type" error, presumably because the Slack flatpak has not acquired the requisite read permissions.

**Comment by ieugen** [comment]
I recommend you use Flatseal https://flathub.org/apps/details/com.github.tchx84.Flatseal 
You can easily add shared folders between your app and home. 
Please come back with feedback if it works.
It might be a valid workaround for others.

**Comment by daniellandau** [comment]
I have the same situation and fix as @ieugen (module a different local language).

**Comment by leadpresence** [comment]
on mobile files are no where to be found

**Comment by erdnaxeli** [comment]
I noticed that if you change the folder in the preferences, it needs a restart to apply the change :shrug: 

Changing the folder that was incorrect and restarting the app fixed the download problem for me.

**Comment by Linux-cpp-lisp** [comment]
I am also having this issue and have not been able to resolve it. When I try to select the correct download folder from within Slack, even after running 
```
sudo flatpak override com.slack.Slack --filesystem=/home/username/Downloads/
```
the `Downloads` folder is still not visible in the file selector. Choosing something like "Documents" which is visible is allowed, but the downloaded files still don't exist there.

How can I resolve this?

**Comment by justdanyul** [comment]
> I am also having this issue and have not been able to resolve it. When I try to select the correct download folder from within Slack, even after running
> 
> ```
> sudo flatpak override com.slack.Slack --filesystem=/home/username/Downloads/
> ```
> 
> the `Downloads` folder is still not visible in the file selector. Choosing something like "Documents" which is visible is allowed, but the downloaded files still don't exist there.
> 
> How can I resolve this?

I’m not trying to troll, but have you considered just using the rpm? Completely unemotional observation from my point, pretty much every single flatpak app I tried had some kind of issue.

**Comment by Linux-cpp-lisp** [comment]
@justdanyul not trolling at all, and you've just solved my problem (deb and not rpm, but same difference). For some reason I had been under the impression that Slack was only officially available as a flatpak or snap, but that is clearly not the case. Thanks!

**Comment by patrolez** [comment]
> I am also having this issue and have not been able to resolve it. When I try to select the correct download folder from within Slack, even after running
> 
> ```
> sudo flatpak override com.slack.Slack --filesystem=/home/username/Downloads/
> ```
> 
> the `Downloads` folder is still not visible in the file selector. Choosing something like "Documents" which is visible is allowed, but the downloaded files still don't exist there.
> 
> How can I resolve this?

Did you replace `username` with your own actual username within provided command snippet?

I have just installed Slack freshly and it worked for me.

If you would like to use it as a script to just copy-paste, so use it as:
`sudo flatpak override com.slack.Slack --filesystem=$HOME/Downloads/`

or use a GUI App to manage flatpak permissions:
https://flathub.org/apps/details/com.github.tchx84.Flatseal

**Comment by Linux-cpp-lisp** [comment]
Yes, I'm pretty sure I did, but maybe there was a typo in the path...

At this point I'm just using the `.deb` which works great.

**Comment by tv42** [comment]
I had a very similar issue with com.google.Chrome and found a fix for my scenario: I went to Chrome's Settings > Downloads > Location, it said /home/myusername/Downloads, I clicked it, re-selected ~/Downloads from the home browser, and now it says /run/user/1000/doc/<8hexdigits>/Downloads and works. No idea if that id in the middle is going to change on the next run or not..

**Comment by bhack** [comment]
Any news on this?

**Comment by ygworldr** [comment]
> Any news on this?

@bhack I just tried `sudo flatpak override com.slack.Slack --filesystem=/home/${USER}/Downloads/` and restarting Slack. This solved it for me. I did not change the default downloads path in Slack, nor do I have a custom `~/.config/user-dirs.dirs`.

**Comment by joelostblom** [comment]
I have the same issue and the suggested workarounds do not fix it, even after restarting slack (will try to restart the machine later).

```
Slack - Chat with your team

          ID: com.slack.Slack
         Ref: app/com.slack.Slack/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.33.84
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 5.4 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 1b49b42e1823047b7946975ad7d51d7eaa9c7041c01fd1cb3c0c44bcd21f1f63
      Parent: ce966b70820ed5191a91273641042fafac5df33eb85af0609ecb482f0cdb1b44
     Subject: Enable Wayland IME when running under Wayland (#191) (a8ceac4d)
        Date: 2023-08-09 10:41:15 +0000
```

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
```

**Comment by razzeee** [comment]
Just touching the settings under `File > Preferences > Advanced` fixed this, so that might be somehow broken with a default setup.

**Comment by ZVNexus** [comment]
I confirmed that the default location on Fedora 39 (GNOME 45.3) and Fedora 40 (KDE Plasma 6) is ${HOME}/Downloads, is this still an issue?

**Comment by ieugen** [comment]
@ZVNexus  It should be `XDG_DOWNLOAD_DIR` . 
I have my linux localized and I don't have $HOME/Downloads I have $HOME/Descărcări :) . 
XDG_DOWNLOAD_DIR points to the right one.

**Comment by ZVNexus** [comment]
@ieugen Can you confirm this issue is fixed after https://github.com/flathub/com.slack.Slack/commit/d869f8b0fc07b3dcd7e8c02948cd1f3c09c1e61f?

**Comment by ieugen** [comment]
@ZVNexus : I downloaded a file and it appeared where it should.  Thanks.
