### ISSUE TITLE
Tray icon incorrect size, Gnome 3.34.1 Fedora 30/31

### ISSUE THREAD

**Issue by jtreminio** [flathub/com.slack.Slack#62]
![image](https://user-images.githubusercontent.com/589398/67304645-c1428500-f4b9-11e9-97ed-6738f14d36f1.png)

Using [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/) and [TopIconsFix](https://extensions.gnome.org/extension/1674/topiconsfix/)

**Comment by TingPing** [comment]
This isn't a packaging issue. I'd probably blame the panel but at the very least it would need more investigation and possibly an upstream but to Slack if the icon is the problem.
