### ISSUE TITLE
blank

### ISSUE THREAD

**Issue by cho2** [flathub/com.slack.Slack#64]
Slack Version: 4.0.2
Flatpak Version: 1.2.3
OS: openSUSE Leap 15.1

![Cuplikan layar dari 2019-11-28 17-41-30](https://user-images.githubusercontent.com/6271071/69799787-87764400-1206-11ea-9037-b9f8c503de57.png)

**Comment by cho2** [comment]
fixed after clear flatpak cache

**Comment by vladimiroff** [comment]
@cho2 could you clarify what exactly did you do to make it running again? I've tried with clearing cache from `/var/tmp/flatpak-cache-*` and `~/.cache/flatpak` (while no flatpak is running of course), clearing app data (`~/.var/app/com.slack.Slack/`) even repairing the app.

Even after all that I'm still only a blank window similar  to what you've posted on the screenshot above.

**Comment by cho2** [comment]
@vladimiroff `rm -r /var/tmp/flatpak-cache-*`
