### ISSUE TITLE
Out of date by a wide margin.

### ISSUE THREAD

**Issue by tinfoil-hacks** [flathub/com.slack.Slack#70]
Current linux version is 4.2.0. This version is 4.0.2. Either that, or there's a typo on the flathub site.

**Comment by cho2** [comment]
> Current linux version is 4.2.0. This version is 4.0.2.

I tried to update to 4.2.0 (#68 #69) but still got an error.

**Comment by wjt** [comment]
This is now causing the app not to start for at least some users:

![Screenshot from 2020-01-22 15-31-13](https://user-images.githubusercontent.com/86760/72907941-ab4c9680-3d2c-11ea-90ae-3c23b323e3ba.png)

**Comment by Cxpher** [comment]
Now i think 4.0.2 does not connect anymore.

**Comment by barthalion** [comment]
Please try zypak-enabled `flatpak install --user https://dl.flathub.org/beta-repo/appstream/com.slack.Slack.flatpakref`. You may need to use `flatpak run com.slack.Slack//beta` afterwards to start it.

@refi64 Do you think it's good enough to merge to master if it turns out to work?

**Comment by z3ntu** [comment]
The beta version also doesn't connect for me:
```
║      Slack 4.2.0, linux 5.4.13-arch1-1 on x64 at 01/27/20, 08:54:26:232      ║
```
```
[01/27/20, 08:55:16:617] info: [NETWORK-CONNECTIVITY] Failed to establish a connection after 7 attempt(s); Retrying in 1000ms. 
[01/27/20, 08:55:17:617] info: [NETWORK-CONNECTIVITY] Testing network connectivity... 
[01/27/20, 08:55:17:618] info: [NETWORK-CONNECTIVITY] Waiting on CDN full backoff. Waiting an additional 6635ms 
[01/27/20, 08:55:17:618] info: [NETWORK-CONNECTIVITY] Failed to establish a connection after 7 attempt(s); Retrying in 6635ms. 
[01/27/20, 08:55:24:253] info: [NETWORK-CONNECTIVITY] Testing network connectivity... 
[01/27/20, 08:55:24:628] info: [NETWORK-CONNECTIVITY] Failed to fetch resources from the CDN with 
AggregateError of:
    Error: Request did not complete.
    Error: Request did not complete.
.
```

**Comment by Cxpher** [comment]
Latest version in AUR connects fine.

**Comment by josefschabasser** [comment]
Please have a look at https://bugs.archlinux.org/task/65284
It seems the new certificates broke pretty much all flatpak apps.

PS: Please update Slack. Version 4.0.2/4.1.1 is severely outdated.

**Comment by Cxpher** [comment]
Hey,

The bug seems valid. I can downgrade the packages of course but I've still
got another gripe with the version being this outdated.

When it's updated, I'll switch back.

**Comment by barthalion** [comment]
If you look at my comment and test the beta build then it will maybe stop being outdated. Feedback is actually more helpful than saying "me too".

**Comment by barthalion** [comment]
Old packages are available at https://archive.archlinux.org. Beta branch ships 4.2.0, I just forgot to update appdata.

**Comment by josefschabasser** [comment]
> Old packages are available at https://archive.archlinux.org. Beta branch ships 4.2.0, I just forgot to update appdata.

Okay, since the beta package couldn't connect, it wasn't possible to open the about window. So I did `flatpak list` and it displayed version 4.1.1. Anyways, the certificate issue should be decoupled from this one. I'll report back tomorrow, because this happened on my office computer and I'm out of office for today 😺

**Comment by Cxpher** [comment]
Hey Josef,

I hear you. Will test it tonight when I'm home.

**Comment by josefschabasser** [comment]
Downgrading the following packages fixed my connection issues with version 4.0.2:
* p11-kit (0.23.19-1 => 0.23.18.1-2)
* ca-certificates-utils (20181109-3 => 20181109-2)
* ca-certificates-mozilla (3.49.2-1 => 3.49.1-1)
* nss (3.49.2-1 => 3.49.1-1)

The beta package is working fine, too (after the downgrade of aforementioned packages).

However, clicking "Help/About Slack" in the menu bar ~~doesn't do anything in both versions (4.0.2 and 4.2.0). There is only one possibility to determine the version: running the app from a terminal prints a header with slack and kernel versions.~~ opens the window on the wrong screen (expected it centered on top of the current window).

I think the certificate discussion here can now be stopped, as this issue must be tackled directly in flatpak upstream: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2247

**Comment by refi64** [comment]
@barthalion Zypak beta has been sitting for a while with no negative results, so I'd think it's all good. IIRC there was someone asking about adding it to the electron baseapp, not sure if that's something Flathub would be interested in to avoid having to update it individually for each Electron app? (Or at least in shared-modules or similar so there's a central point of updates.)

EIther way I'll be tagging a non-beta Zypak release today or tomorrow.

**Comment by barthalion** [comment]
@refi64 Yeah, it probably makes sense to have it in BaseApp. I'll handle it.

I also merged `beta` branch to `master` so closing this issue.
