### ISSUE TITLE
Can't Access $HOME on Slack 4.3.2

### ISSUE THREAD

**Issue by cho2** [flathub/com.slack.Slack#73]
OS: openSUSE Tumbleweed
Flatpak version: 1.6.1

```
flatpak info com.slack.Slack

Slack - Chat with your team

        ID: com.slack.Slack
       Ref: app/com.slack.Slack/x86_64/beta
Arsitektur: x86_64
    Cabang: beta
     Versi: 4.3.2
   Lisensi: LicenseRef-proprietary
      Asal: flathub-beta
   Koleksi: org.flathub.Beta
Pemasangan: system
 Terpasang: 3,0 MB
   Runtime: org.freedesktop.Platform/x86_64/19.08
       Sdk: org.freedesktop.Sdk/x86_64/19.08

     Komit: b729c0b8a4c33f3b728f2f63bbf0872361ac7851c5f228b6c19dac9b0a3b60e8
     Induk: 647c2d5c645bd561127a5203586452ea109f95cdac1ae8c2c750d9985bb2b62a
    Subjek: Update to 4.3.2 (ad235114)
   Tanggal: 2020-02-05 06:12:37 +0000
```

Already run `flatpak run --filesystem=home com.slack.Slack` and `sudo flatpak override --filesystem=home com.slack.Slack` (as described on `README.md`), but still can't access files and other folders on $HOME

**Comment by bcaccia** [comment]
I think that I'm experiencing the same issue.

* OS: Manjaro Gnome Edition, Stable branch
* Flatpak 1.8.1
* Slack Flatpak 4.11.1

**Repro:**

1. In Slack, click on the paperclip icon to attach a file and click on the **Your Computer** option
![image](https://user-images.githubusercontent.com/23156454/99074483-d3400b80-2585-11eb-9fb6-77a6b87bc298.png)

**Expected:**
* The full contents of the users HOME directory will be accessible

**Bug:** 
Only a subset of folders in the users home directory are available
![image](https://user-images.githubusercontent.com/23156454/99074723-49dd0900-2586-11eb-8e1b-b7dbe62c532e.png)

I think the reason for this is that those specific directories are explicitly defined on these lines here, meaning you can access just them and not the entire HOME directory:
https://github.com/flathub/com.slack.Slack/blob/master/com.slack.Slack.json#L16-L20

This issue does not exist in another Flatpak that I use, KeepassXC. Their filesystem definitions are located here:
https://github.com/flathub/org.keepassxc.KeePassXC/blob/master/org.keepassxc.KeePassXC.yml#L30-L45

I don't know anything about Flatpak packaging, but I think the `- --filesystem=host` may be the key, at least what I can tell from viewing the documentation here:
https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-metadata

Apologies for the giant screenshot, can't seem to hotlink to a specific section in the documentation
![image](https://user-images.githubusercontent.com/23156454/99075624-c7554900-2587-11eb-86ec-8ad6c5399c7b.png)

**Comment by FakeShemp** [comment]
If you want to override access, use https://flathub.org/apps/details/com.github.tchx84.Flatseal or command line arguments to do so. The app will be restrictive by default.

**Comment by FakeShemp** [comment]
Overrides seem to work now.
