### ISSUE TITLE
Flatpak app doesn't save launch on session start option

### ISSUE THREAD

**Issue by alexbaforvo** [flathub/com.slack.Slack#8]
In the flatpak version of the app, in the settings > linux application menu, the first option to launch the app on session start doesn't work. If I select the checkbox, the app shows the "saved" message, but the next time I start my session, the app doesn't launch by default.

Current flatpak app version installed:  3.0.5 64-bit

**Comment by TingPing** [comment]
This is simply not doable since it is in a sandbox and the auto launch file it generates wouldn't be use-able anyway.

You can manually copy the flatpak desktop file into `~/.config/autostart` for now.
