### ISSUE TITLE
URLs don't get opened by the default system browser

### ISSUE THREAD

**Issue by butla** [flathub/com.slack.Slack#82]
Some time ago Slack on my Manjaro install started to open up URLs on Chromium, instead of my default browser - Brave (`xdg-settings get default-web-browser` gives me `brave-browser.desktop`).

When i run `flatpak run --command=bash com.slack.Slack` and try xdg-open it opens Brave correctly.

Also, the version on Snap opens links correctly.

After I removed Chromium from my system the links stopped opening at all. The other browsers on my system is Firefox.

Can this be an issue of how this app is packaged, or is it a problem with something like https://github.com/flatpak/xdg-desktop-portal?

**Comment by FakeShemp** [comment]
People have reported similar problems on Windows even, so I'm stumped at what actually causes this.

If you have an inkling of a idea what causes this I'd be very happy to try to solve it.

**Comment by FakeShemp** [comment]
@butla What does `xdg-settings get default-url-scheme-handler https` give you for result?

**Comment by butla** [comment]
Oh... what's interesting. I get `xdg-settings: default-url-scheme-handler not implemented for xfce`

**Comment by rockon999** [comment]
When I run `xdg-settings get default-url-scheme-handler https`, I get `firefox.desktop` which is my default browser. Slack always opens in Chromium though. My default browser used to be Chromium, but it isn't anymore and this only appears in Slack as best I can tell.

**Comment by rockon999** [comment]
I think this is probably related to #34.

**Comment by kisst** [comment]
Same behavior, the related log entry looks like this:
```
Jul 27 09:05:09 localhost com.slack.Slack.desktop[8834]: Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.OpenURI? on object at path /org/freedesktop/portal/desktop
```
Running the latest version:
```
$ flatpak list | grep Slack
Slack   com.slack.Slack 4.7.0   stable  system
```

This is the case for all links, like Support ticket,s adding extra work spaces, or just links from the chat.
Happy to help debugging this issue.

**Comment by kisst** [comment]
@butla I suggest to update the issue desc as it's apparent that it's not distro related issue.

**Comment by fungos** [comment]
I'm having the same issue here.

```➜  ~ xdg-settings get default-url-scheme-handler https
firefox.desktop
➜  ~ xdg-settings get default-web-browser             
firefox.desktop
➜  ~ echo $BROWSER
/usr/bin/xdg-open
➜  ~ cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.1
DISTRIB_CODENAME=Mikah
DISTRIB_DESCRIPTION="Manjaro Linux"
 ```
KDE has the default browser also set to Firefox.

**Comment by fungos** [comment]
So a quick update. I think there is something with flatpak package installation.

After I launched it via console one time, all subsequent launches via KDE menu picked the right browser even after a reboot. So, there may be something stale somewhere that doesn't get updated.

I can't remember ever having Chromium as a default browser, but maybe I did add the `$BROWSER` long time ago AFTER installing the flatpak, when I was trying to force Slack to pick the right one. But recently when posting the issue above and launched from console, it got to fix the issue elsewhere permanently.

**Comment by talhajunaidd** [comment]
https://github.com/flatpak/flatpak/issues/1508#issuecomment-374955765

**Comment by othbert** [comment]
Just in case anyone else has the same thing, for me the `xdg-settings get default-web-browser` gave the correct browser but `xdg-settings get default-url-scheme-handler https` the wrong one. Not sure why the Slack package isn't using default-web-browser (on opensuse tw / kde) but setting the correct browser for the https scheme handler made it work properly.

**Comment by mcamou** [comment]
For me (Kubuntu 20.10), `xdg settings get default-web-browser`, `xdg-settings get default-url-scheme-handler https` and `xdg-settings get default-url-scheme-handler http` all return the correct browser (Brave) but Slack always opens links using Chrome.

**Comment by WhyNotHugo** [comment]
@mcamou This is an issue tracker for the Flatpak package, no the Snap one.

**Comment by fmichaut-dev** [comment]
Hello,
I'm here to report the same issue, happens to me in Discord, when I click on a link it opens with Firefox even tho `xdg-settings get default-web-browser` is set to chrome. 
Although, if I delete (or rename) /bin/firefox, then it does open the link with chrome.

I am on xfce so the output of `xdg-settings get default-url-scheme-handler https` is `xdg-settings: default-url-scheme-handler not implemented for xfce`.

I would like to see this issue solved, since I am often opening links from Discord

**Comment by othbert** [comment]
Issue has started again with the latest flatpak release of Slack.
http, https schemes and web-browser all set to the correct browser but links don't even open at all anymore.

**Comment by sameyepatch** [comment]
Hello, for those whose XFCE system show `xdg-settings: default-url-scheme-handler not implemented for xfce` for the http/https handler AND have `xdg-desktop-portal` installed, you can use this workaround https://github.com/flatpak/flatpak/issues/3216

**Comment by evan-a-a** [comment]
Closing due to age.
