### ISSUE TITLE
Slack via flathub doesn't take into account scaling in Wayland

### ISSUE THREAD

**Issue by maxamillion** [flathub/com.slack.Slack#85]
If you run Wayland on a HiDPI display and enable display scaling in GNOME (3.36 at the time of this writing), either full or fractional, the Slack window doesn't render fonts accordingly. Supposedly [this can be set as per the Arch wiki](https://wiki.archlinux.org/index.php/HiDPI#Slack) but I've not been able to make it function as documented in that wiki if I make the suggested edits to `/home/admiller/.local/share/flatpak/app/com.slack.Slack/x86_64/stable/03ed7b6d823f379e26c7c0251ed0f61bfc22eaebf395128f658949bdbedb7d5b/files/extra/share/applications/slack.desktop`.

**Comment by FakeShemp** [comment]
As far as I know, Electron itself does not support Wayland, so this will never be possible.

If you want to hack it like Arch tells you, you run `flatpak run com.slack.Slack --force-device-scale-factor=1.5`

**Comment by klemmster** [comment]
Since slack supports wayland now, I've been able to run it successfully with the following command:
```
 flatpak run --socket=wayland com.slack.Slack --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland
```
This solved the scaling issue as well. However, it seems there's no header bar support (CSD) yet available in electron apps'.
