### ISSUE TITLE
Message timestamps wrong after DST change

### ISSUE THREAD

**Issue by mattlong-finocomp** [flathub/com.slack.Slack#94]
I'm seeing a similar problem to https://github.com/flathub/com.slack.Slack/issues/43 except my timestamps were correct until the recent Daylight Savings Time change observed in Sydney Australia.
```
$ timedatectl
               Local time: Thu 2020-10-08 13:34:27 AEDT  
           Universal time: Thu 2020-10-08 02:34:27 UTC   
                 RTC time: Thu 2020-10-08 02:34:27       
                Time zone: Australia/Sydney (AEDT, +1100)
System clock synchronized: yes                           
              NTP service: active                        
          RTC in local TZ: no     
```

Using this workaround fixed the issue for me: https://github.com/flathub/com.slack.Slack/issues/43#issuecomment-530164518

As an aside I noticed that changing the Time zone in Preferences had no impact to the timestamps shown on messages.

**Comment by iosdevben** [comment]
This just happened to me, in Oct 2023.

**Comment by shangeethas** [comment]
Same here, wrong time stamp in Slack messages in October 2023. The slack messages timestamp has not been updated after yesterday's daylight savings.

**Comment by Hoody91** [comment]
Can confirm is happening to me as well. 

Version 4.34.121
db7e6a373f5813123dcb34e93418803679a066c5@1696283848 (Production)

**Comment by ZVNexus** [comment]
@Hoody91 Can you still verify that it's happening?

**Comment by Hoody91** [comment]
@ZVNexus Can confirm this is no longer happening. 

Version 4.35.132
da9c862cec6598e0ef1f1528d7248f58c8328c26@1705190841 (Production)
